In [86]:
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn import linear_model

from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

In [105]:
ML_df = pd.read_csv(Path(r'C:\Users\helen\Desktop\Berkeley boot camp\Datasets\carbon_emission_analysis\Jupyter notebook/ml_database2.csv'))
ML_df.head()

,Unnamed: 0,Facility Id,State,industry_type,year,total_direct_emissions,state_population,state_gdp_per_capita,state_policies_incentives,USDA_energy_invest_unit,USDA_energy_invest_$,%Renewables
0,0,1004377,TX,Waste Management and Remediation Services,2016,221014.750,27914064,58033.62062,140,176,83600842.01,13.4
1,1,1003188,TX,Plastics and Rubber Products Manufacturing,2016,31773.480,27914064,58033.62062,140,176,83600842.01,13.4
2,2,1007733,TX,Utilities,2016,22362.816,27914064,58033.62062,140,176,83600842.01,13.4
3,3,1002685,TX,Oil and Gas Extraction,2016,265377.770,27914064,58033.62062,140,176,83600842.01,13.4
4,4,1005601,TX,Nonmetallic Mineral Product Manufacturing,2016,55858.240,27914064,58033.62062,140,176,83600842.01,13.4

In [107]:
# Select the columns we need for the linear regression
ML_df = ML_df.drop(columns = ["Facility Id", "year"], axis = 1)

In [108]:
# Transform the categorical features into numerical data
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
ML_df['State'] = le.fit_transform(ML_df['State'])
ML_df['industry_type'] = le.fit_transform(ML_df['industry_type'])
ML_df

,Unnamed: 0,State,industry_type,total_direct_emissions,state_population,state_gdp_per_capita,state_policies_incentives,USDA_energy_invest_unit,USDA_energy_invest_$,%Renewables
0,0,9,41,221014.750,27914064,58033.62062,140,176,83600842.01,13.4
1,1,9,30,31773.480,27914064,58033.62062,140,176,83600842.01,13.4
2,2,9,39,22362.816,27914064,58033.62062,140,176,83600842.01,13.4
3,3,9,26,265377.770,27914064,58033.62062,140,176,83600842.01,13.4
4,4,9,25,55858.240,27914064,58033.62062,140,176,83600842.01,13.4
...,...,...,...,...,...,...,...,...,...,...
15636,30218,7,41,27637.500,3980783,47953.83220,41,5,112008.16,37.1
15637,30219,7,29,62438.954,3980783,47953.83220,41,5,112008.16,37.1
15638,30220,7,26,32642.260,3980783,47953.83220,41,5,112008.16,37.1
15639,30221,7,28,743181.048,3980783,47953.83220,41,5,112008.16,37.1
15640,30222,7,39,1683.944,3980783,47953.83220,41,5,112008.16,37.1

In [116]:
ML_df = ML_df.drop(columns = ["Unnamed: 0"], axis = 1)

In [117]:
ML_df.value_counts("State")

State
9    3916
3    2042
0    1981
8    1407
6    1257
2    1241
4    1079
5    1023
1     869
7     826
dtype: int64

In [118]:
# Define the features set
X = ML_df.copy()
X = X.drop("total_direct_emissions", axis=1)
X.head()

,State,industry_type,state_population,state_gdp_per_capita,state_policies_incentives,USDA_energy_invest_unit,USDA_energy_invest_$,%Renewables
0,9,41,27914064,58033.62062,140,176,83600842.01,13.4
1,9,30,27914064,58033.62062,140,176,83600842.01,13.4
2,9,39,27914064,58033.62062,140,176,83600842.01,13.4
3,9,26,27914064,58033.62062,140,176,83600842.01,13.4
4,9,25,27914064,58033.62062,140,176,83600842.01,13.4

In [122]:
# Define the target set.
y = ML_df["total_direct_emissions"].values
y[:5]

array([221014.75 ,  31773.48 ,  22362.816, 265377.77 ,  55858.24 ])

In [123]:
# Split the Data Into Training and Testing Sets into an 80/20 split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, train_size=0.75)

In [124]:
# Scale the Training and Testing Data
scaler = StandardScaler()

# Fit and scale the Standard Scaler with the training data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [125]:
#  Create the decision tree regressor instance
model = DecisionTreeRegressor(random_state=0)

# Fit Model
model = model.fit(X_train_scaled, y_train)

In [126]:
print(model.score(X_train_scaled, y_train))
print(model.score(X_test_scaled, y_test))

0.22022595121523159
0.17111367634544317

In [127]:
# Make predictions using the testing data
predictions = model.predict(X_test_scaled)
predictions

array([ 24057.298     , 954876.8883871 , 275102.69061818, ...,
        43664.74292683,  38273.456     ,  68999.78653896])

In [128]:
# Test the balanced accuracy score of the model
from sklearn.metrics import r2_score
r2_score(y_test, predictions)

0.17111367634544317